# Generated by Django 5.2.5 on 2025-09-16 14:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PELI_REG', '0002_rename_task_peliculas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='peliculas',
            new_name='Peliculass',
        ),
    ]
